import { TranslationContent } from "./types";

export const translations: { nl: TranslationContent; en: TranslationContent } = {
  nl: {
    hero: {
      badge: "Praktijktraining in 1 dag",
      title: "AI voor IT-professionals",
      subtitle: "Begrijp AI vandaag. Gebruik het morgen.",
      ctaPrimary: "Reserveer mijn plaats",
      ctaSecondary: "Bekijk programma",
      duration: "1 Dag",
      location: "Ridderkerk",
      date: "26 sep 2026",
    },
    intro: {
      title: "AI Verandert het IT-landschap",
      lead: "Artificial Intelligence (AI) verandert de manier waarop IT-professionals werken. Van softwareontwikkeling en systeembeheer tot documentatie, security en automatisering: AI wordt steeds vaker onderdeel van het dagelijkse werk.",
      description: "Tijdens deze praktijkgerichte eendaagse training leer je hoe AI werkt en hoe je AI veilig en verantwoord inzet binnen jouw dagelijkse IT-werkzaamheden. Je werkt met herkenbare praktijkvoorbeelden, live demonstraties en hands-on oefeningen die je direct kunt toepassen. Na afloop kun je met vertrouwen meepraten over AI én heb je de kennis en praktische handvatten om AI vanaf de volgende werkdag slimmer in te zetten binnen jouw eigen organisatie.",
      promiseTitle: "Onze belofte",
      promiseText: "Je verlaat deze training niet als AI-expert, maar als een IT-professional die begrijpt wat AI kan, de juiste vragen weet te stellen en direct kansen ziet om AI toe te passen in het dagelijkse IT-werk.",
      whyJoinTitle: "Waarom deelnemen?",
      whyJoinPoints: [
        "Begrijp de basis van Artificial Intelligence (AI) en Large Language Models (LLM's)",
        "Leer betere prompts schrijven voor technische vraagstukken",
        "Pas AI toe in je dagelijkse IT-werkzaamheden",
        "Werk veiliger met AI dankzij aandacht voor privacy, security en governance",
        "Neem direct toepasbare kennis en praktische voorbeelden mee naar je werk",
      ],
      painPointsTitle: "Herken je dit?",
      painPoints: [
        "Je collega's praten steeds vaker over AI, ChatGPT of Microsoft Copilot.",
        "Je hebt AI al eens geprobeerd, maar weet niet goed hoe je het effectief inzet.",
        "Je vraagt je af welke AI-tools écht waarde toevoegen aan jouw werk.",
        "Je wilt slimmer en efficiënter werken zonder in te leveren op kwaliteit of veiligheid.",
        "Je zoekt een praktische training zonder ingewikkelde theorie of marketingverhalen.",
      ],
    },
    objectives: {
      title: "Wat levert deze training je op?",
      subtitle: "Concrete vaardigheden en direct toepasbare inzichten voor de moderne IT-praktijk",
      items: [
        {
          title: "Met vertrouwen meepraten",
          description: "Begrijp en bespreek de belangrijkste AI-concepten met vertrouwen binnen jouw team of organisatie.",
        },
        {
          title: "Begrijp hoe AI-tools werken",
          description: "Krijg diepgaand inzicht in de werking van LLM's, tokens, context en de architectuur van generatieve AI.",
        },
        {
          title: "Schrijf superieure prompts",
          description: "Leer effectieve en geavanceerde prompt-technieken specifiek ontworpen voor technische vraagstukken.",
        },
        {
          title: "Directe IT-toepassing",
          description: "Ontdek hoe je AI onmiddellijk inzet voor code generatie, reviews, troubleshooting en documentatie.",
        },
        {
          title: "Privacy & Security borging",
          description: "Weet exact wat wel en niet ingevoerd mag worden volgens de AVG en beheers de governance-risico's.",
        },
        {
          title: "Kansen in kaart brengen",
          description: "Herken strategische kansen om AI slimmer toe te passen en stel een concreet stappenplan op.",
        },
      ],
    },
    audience: {
      title: "Voor wie is deze training?",
      subtitle: "Speciaal ontwikkeld voor IT-professionals die AI praktisch willen inzetten",
      description: "Deze training is ontwikkeld voor IT-professionals die willen begrijpen hoe Artificial Intelligence (AI) hun werk verandert én hoe zij AI direct kunnen inzetten in hun dagelijkse werkzaamheden. Je hoeft geen ervaring met AI te hebben. Een algemene IT-achtergrond is voldoende.",
      requirementsTitle: "Voorkennis",
      requirementsText: "Je hebt geen ervaring met Artificial Intelligence (AI) nodig. Wel is het handig wanneer je ervaring hebt met IT-werkzaamheden.",
      tasksTitle: "Ideaal als je regelmatig bezig bent met:",
      tasksList: [
        "Software ontwikkelen of onderhouden",
        "Systeem- en netwerkbeheer",
        "Troubleshooting en incidentmanagement",
        "Technische documentatie opstellen",
        "Logbestanden analyseren",
        "Configuraties beheren",
        "Security en compliance",
        "Automatisering van terugkerende IT-processen",
      ],
      idealTitle: "Deze training is perfect als:",
      idealList: [
        "Je wilt begrijpen waar iedereen het over heeft als het over AI gaat.",
        "Je wilt maandag met vertrouwen meepraten over AI.",
        "Je wilt tijd besparen op terugkerende werkzaamheden.",
        "Je wilt AI veilig en verantwoord gebruiken.",
        "Je zoekt een praktische training zonder ingewikkelde theorie.",
      ],
      notForTitle: "Wanneer is deze training niet geschikt?",
      notForText: "Dit is een introductietraining voor IT-professionals. Ben je al dagelijks diepgaand bezig met Prompt Engineering, AI-ontwikkeling en zoek je een diepgaande machine learning training? Dan sluit een gevorderde AI-training waarschijnlijk beter aan bij jouw kennisniveau.",
    },
    program: {
      title: "Programma van de dag",
      subtitle: "Een intensief en praktijkgericht eendaags programma van 09:00 tot 17:00 uur",
      timeline: [
        {
          time: "09:00 – 09:30",
          title: "Introductie & AI-landschap",
          description: "We starten de dag met een kennismaking en verkennen het huidige landschap van AI.",
        },
        {
          time: "09:30 – 10:45",
          title: "Begrijpen hoe AI werkt",
          description: "Ontdek hoe Large Language Models (LLM's) onder de motorkap werken.",
        },
        {
          time: "10:45 – 11:00",
          title: "Ochtendpauze",
          description: "Een korte break voor koffie en thee.",
        },
        {
          time: "11:00 – 12:30",
          title: "Prompting voor IT-professionals",
          description: "Leer gestructureerde, effectieve prompts schrijven.",
        },
        {
          time: "12:30 – 13:15",
          title: "Verzorgde lunch",
          description: "Geniet van een gezonde, compleet verzorgde lunch.",
        },
        {
          time: "13:15 – 14:45",
          title: "AI als jouw software-assistent",
          description: "Ontdek hoe je AI inzet als assistent.",
        },
        {
          time: "14:45 – 15:00",
          title: "Middagpauze",
          description: "Korte pauze om even op te frissen en energie op te laden.",
        },
        {
          time: "15:00 – 16:00",
          title: "Security, Privacy en Governance",
          description: "Leer hoe je AI veilig, AVG-compliant en verantwoord inzet.",
        },
        {
          time: "16:00 – 17:00",
          title: "Workshop: AI-use cases binnen de eigen organisatie",
          description: "Breng concrete AI-kansen voor jouw organisatie in kaart.",
        },
      ],
    },
    practical: {
      title: "Praktische Informatie",
      subtitle: "Alles wat je moet weten om optimaal voorbereid aan de training te beginnen",
      dateLabel: "Datum",
      dateValue: "Zaterdag 26 september 2026",
      locationLabel: "Locatie",
      locationValue: "Noordenweg 24, Ridderkerk",
      locationDetails: "Uitstekend bereikbaar. Exacte zaal- en route-informatie ontvang je direct na inschrijving.",
      timeLabel: "Tijd",
      timeValue: "09:00 – 17:00 uur",
      timeDetails: "Inloop en ontvangst starten vanaf 08:45 uur. Zorg dat je op tijd bent voor een warme bak koffie!",
      includesLabel: "Inclusief",
      includesList: [
        "Volledige en intensieve trainingsdag",
        "Heerlijke, uitgebreide lunch",
        "Onbeperkt koffie, thee en versnaperingen",
        "Een flinke dosis humor en inspiratie",
      ],
      bringLabel: "Wat neem je mee?",
      bringValue: "Eigen laptop",
      bringRecommended: [
        "Een laptop met Wi-Fi mogelijkheid",
        "Toegang tot een AI-tool zoals ChatGPT (een gratis account is ruim voldoende)",
      ],
      groupSizeLabel: "Groepsgrootte",
      groupSizeValue: "Maximaal 10 deelnemers",
      levelLabel: "Niveau",
      levelValue: "Beginnend tot gemiddeld",
      levelDetails: "Geen specifieke AI-voorkennis vereist. Basiskennis van IT of IT-werkzaamheden is voldoende.",
      investmentLabel: "Investering",
      originalPrice: "€799",
      discountPrice: "€199",
      priceDetails: "Tijdelijke introductieprijs / Early Bird actie. Prijzen zijn per persoon en inclusief lunch en drankjes. Je ontvangt achteraf een btw-factuur.",
      afterRegisterLabel: "Na je inschrijving",
      afterRegisterValue: [
        "Directe e-mail met ontvangstbevestiging en vervolgstappen.",
      ],
    },
    trainer: {
      title: "Jouw Trainers & Organisatie",
      subtitle: "Leren van ervaren IT-professionals met passie voor verantwoorde AI",
      intro: "Deze training wordt verzorgd door ervaren IT-professionals vanuit Stichting Duurzaam AI. Geen theoretische verhalen, maar een hands-on aanpak gebaseerd op de dagelijkse praktijk van IT-professionals.",
      aboutFoundationTitle: "Over Stichting Duurzaam AI",
      aboutFoundationText: "Stichting Duurzaam AI helpt professionals en organisaties om Artificial Intelligence op een praktische, veilige en verantwoorde manier toe te passen. Wij richten ons niet op de hype of marketingverhalen rondom AI, maar op de cruciale vraag: Hoe kan AI-vooruitgang hand in hand gaan met maatschappelijke waarden, AVG-compliance en ethiek?",
      trainerCardTitle: "Ontmoet de docenten",
      trainers: [
        {
          name: "Sayf Jawad",
          role: "Software Architect & AI Specialist",
          bio: "Sayf heeft meer dan 15 jaar ervaring in softwareontwikkeling, softwarearchitectuur en AI. Hij helpt organisaties bij het ontwikkelen van toekomstbestendige software en het verantwoord inzetten van generatieve AI, met een sterke focus op kwaliteit, privacy en praktische toepasbaarheid.",
          initials: "SJ",
          experience: "15+ jaar ervaring in Software & AI",
          linkedinUrl: "https://www.linkedin.com/in/sayf-jawad-511100300/",
        },
        {
          name: "Manhal AL-Rubaiy",
          role: "Senior Data & AI Engineer",
          bio: "Manhal heeft meer dan 15 jaar ervaring in Business Intelligence, data engineering en AI. Hij helpt organisaties en IT-professionals om generatieve AI veilig en praktisch toe te passen, met direct bruikbare oplossingen voor de dagelijkse praktijk.",
          initials: "MA",
          experience: "15+ jaar ervaring in Data & AI",
          linkedinUrl: "https://www.linkedin.com/in/manhal-al-rubaiy",
        },
      ],
      approachTitle: "Onze Aanpak",
      approachIntro: "Wij geloven dat AI pas echt waarde toevoegt wanneer professionals doorzien hoe het werkt, waar de risico's liggen en hoe je het ethisch en veilig toepast. Daarom combineren we:",
      approachPoints: [
        "Jarenlange praktische IT-ervaring",
        "Actuele en diepgaande AI-kennis",
        "Live demonstraties op reële systemen",
        "Herkenbare en realistische praktijkvoorbeelden",
        "Interactieve en uitdagende hands-on oefeningen",
      ],
    },
    faq: {
      title: "Veelgestelde Vragen",
      subtitle: "Antwoorden op de meest voorkomende vragen over de training",
      items: [
        {
          question: "Heb ik voorafgaande kennis van Artificial Intelligence nodig?",
          answer: "Nee, absoluut niet. Deze training is speciaal ontwikkeld voor IT-professionals die vanaf de basis willen begrijpen wat AI kan betekenen voor hun werk. Een algemene achtergrond of ervaring in IT is ruim voldoende.",
        },
        {
          question: "Moet ik goed kunnen programmeren om deel te nemen?",
          answer: "Nee. Hoewel we tijdens het onderdeel 'AI als Software-assistent' praktijkvoorbeelden gebruiken die te maken hebben met code, reviews en scripting, ligt de nadruk op het begrijpen, aansturen en toepassen van de AI. IT-professionals zonder diepe programmeerervaring (zoals systeembeheerders of IT-managers) kunnen hier prima aan deelnemen.",
        },
        {
          question: "Kan mijn werkgever deze training betalen?",
          answer: "Ja, zeker! De overgrote meerderheid van onze deelnemers volgt deze training via hun werkgever. Na je inschrijving sturen we een professionele btw-factuur die ingediend kan worden bij de administratie van jouw organisatie.",
        },
        {
          question: "Wat kan ik concreet na afloop van deze trainingsdag?",
          answer: "Je begrijpt hoe LLM's werken, hoe je effectieve prompts schrijft die direct bruikbare resultaten opleveren, hoe je AI inzet als coding- en documentatie-assistent, en hoe je veilig en AVG-compliant met data omgaat. Daarnaast ga je naar huis met een concreet stappenplan om AI-kansen binnen je eigen organisatie te prioriteren.",
        },
        {
          question: "Welke specifieke AI-tools worden er behandeld?",
          answer: "We bespreken en demonstreren diverse toonaangevende AI-tools (waaronder ChatGPT, Microsoft Copilot en specifieke coding assistants). De focus ligt echter niet op één specifieke tool, maar op de universele concepten en vaardigheden waarmee je elke huidige én toekomstige AI-tool effectief en verantwoord leert beheersen.",
        },
        {
          question: "Moet ik mijn eigen laptop meenemen?",
          answer: "Ja. Omdat het een zeer actieve, praktijkgerichte training is, werk je op je eigen laptop. We adviseren een laptop met Wi-Fi en een (gratis) account op een AI-tool zoals ChatGPT.",
        },
        {
          question: "Is de lunch inbegrepen in de prijs?",
          answer: "Ja! De training is volledig ontzorgd. Dit betekent dat een uitgebreide lunch, onbeperkt koffie en thee, frisdranken en diverse tussendoortjes volledig bij de prijs zijn inbegrepen.",
        },
        {
          question: "Wat zijn de annuleringsvoorwaarden?",
          answer: "Je kunt tot 14 dagen voor de training volledig kosteloos annuleren. Bij annulering binnen 14 dagen wordt 50% van het deelnamebedrag in rekening gebracht. Binnen 7 dagen of bij afwezigheid (no-show) is het volledige bedrag verschuldigd. Mocht je zelf verhinderd zijn, dan mag je kosteloos een vervanger aanwijzen. Stuur ons hiervoor uiterlijk één werkdag van tevoren een e-mail.",
        },
      ],
    },
    stats: {
      eyebrow: "IN CIJFERS",
      title: "Statistieken",
      subtitle: "Live cijfers over de belangstelling voor deze training.",
      seatsLabel: "Beschikbare plekken",
      seatsFilled: "plekken gevuld",
      seatsFull: "Vol",
      totalRegistrations: "Inschrijvingen",
      totalVisitors: "Websitebezoeken",
      experienceBreakdownTitle: "IT-ervaring van deelnemers",
      loading: "Statistieken laden...",
      error: "Statistieken konden niet worden geladen.",
    },
    registration: {
      title: "Inschrijven & Plaats Reserveren",
      subtitle: "Reserveer nu je plaats voor de training op zaterdag 26 september 2026. Let op: maximaal 10 deelnemers!",
      formTitle: "Inschrijfformulier",
      personalData: "Persoonlijke Gegevens",
      firstName: "Voornaam *",
      lastName: "Achternaam *",
      email: "E-mailadres *",
      phone: "Telefoonnummer",
      workData: "Werk- & Ervaringsgegevens",
      organization: "Organisatie",
      function: "Functie",
      experience: "Aantal jaren IT-ervaring",
      experienceOptions: ["0–2 jaar", "3–5 jaar", "5–10 jaar", "10+ jaar"],
      invoiceData: "Factuurgegevens",
      invoiceRequired: "Factuur op naam van organisatie?",
      invoiceRequiredYes: "Ja, stuur factuur naar organisatie",
      invoiceRequiredNo: "Nee, particuliere factuur",
      companyName: "Bedrijfsnaam *",
      invoiceAddress: "Factuuradres *",
      postalCodeCity: "Postcode en Plaats *",
      vatNumber: "BTW-nummer (indien van toepassing)",
      dietaryLabel: "Heb je dieetwensen?",
      dietaryOptions: [
        { label: "Geen dieetwensen", value: "Geen" },
        { label: "Vegetarisch", value: "Vegetarisch" },
        { label: "Veganistisch", value: "Vegan" },
        { label: "Allergie / Anders", value: "Allergie" },
      ],
      dietaryPlaceholder: "Geef eventuele allergieën of dieetwensen op...",
      remarksLabel: "Opmerkingen of vragen",
      remarksPlaceholder: "Heb je specifieke vragen of wensen? Stel ze hier...",
      consentTerms: "Ik ga akkoord met de algemene voorwaarden van Stichting Duurzaam AI. *",
      consentPrivacy: "Ik heb de privacyverklaring gelezen en ga akkoord met de verwerking van mijn gegevens voor deze inschrijving. *",
      submitBtn: "Reserveer mijn plaats",
      submitting: "Verwerken...",
      successTitle: "Reservering Succesvol Ontvangen!",
      successText: "Gefeliciteerd! Je plaats voor de training 'AI voor IT-professionals' op zaterdag 26 september 2026 is gereserveerd.",
      successSteps: [
        "Je ontvangt direct een automatische bevestigingsmail van je reservering, met de vervolgstappen.",
        "E-mail niet ontvangen? Controleer eerst je spam- of ongewenste e-mailmap. Kun je de e-mail daar ook niet vinden? Neem dan contact op met Stichting Duurzaam AI via info@stichtingduurzaamai.nl.",
      ],
      validationError: "Vul alstublieft alle verplichte velden (*) correct in.",
      privacyLink: "Privacyverklaring (AVG)",
      termsLink: "Algemene Voorwaarden",
    },
    footer: {
      tagline: "Stichting Duurzaam AI - Samen naar een verantwoorde, veilige en duurzame AI-toekomst.",
      contact: "Contactgegevens",
      rights: "© 2026 Stichting Duurzaam AI. Alle rechten voorbehouden.",
      privacy: "Privacyverklaring",
      terms: "Algemene Voorwaarden",
      adminPanel: "Beheerderspaneel (Inschrijvingen)",
    },
  },
  en: {
    hero: {
      badge: "Practical training in 1 day",
      title: "AI for IT Professionals",
      subtitle: "Understand AI today. Use it tomorrow.",
      ctaPrimary: "Reserve my spot",
      ctaSecondary: "View program",
      duration: "1 Day",
      location: "Ridderkerk (NL)",
      date: "Sep 26, 2026",
    },
    intro: {
      title: "AI is Changing the IT Landscape",
      lead: "Artificial Intelligence (AI) is transforming how IT professionals work. From software development and systems engineering to documentation, security, and automation: AI is increasingly becoming a core part of daily tasks.",
      description: "During this practical, one-day training course, you will learn how AI works and how to apply it safely and responsibly within your daily IT operations. You will work with highly recognizable real-world examples, live demonstrations, and hands-on exercises that you can apply immediately. By the end, you will be able to discuss AI with complete confidence and possess the practical tools to utilize AI smarter from the very next workday.",
      promiseTitle: "Our Promise",
      promiseText: "You will not leave this training as an AI academic, but as an IT professional who thoroughly understands what AI can do, knows how to ask the right questions, and immediately spots concrete opportunities to implement AI in everyday IT work.",
      whyJoinTitle: "Why Join?",
      whyJoinPoints: [
        "Grasp the fundamentals of Artificial Intelligence (AI) and Large Language Models (LLMs)",
        "Learn how to write superior prompts tailored for technical issues",
        "Apply AI directly in your daily IT routines",
        "Work safer with AI through focus on privacy, security, and governance",
        "Take home immediately applicable knowledge and practical templates",
      ],
      painPointsTitle: "Recognize this?",
      painPoints: [
        "Your colleagues talk more and more about AI, ChatGPT, or Microsoft Copilot.",
        "You have tried AI before, but don't quite know how to leverage it effectively.",
        "You wonder which AI tools actually bring genuine value to your daily tasks.",
        "You want to work smarter and more efficiently without sacrificing quality or safety.",
        "You are looking for a practical training course without complex theory or marketing hype.",
      ],
    },
    objectives: {
      title: "What will this training bring you?",
      subtitle: "Concrete skills and immediately applicable insights for modern IT operations",
      items: [
        {
          title: "Speak with Confidence",
          description: "Understand and discuss key AI concepts with total confidence within your team or company.",
        },
        {
          title: "Understand How AI Works",
          description: "Gain deep insights into how LLMs, tokens, context length, and generative AI architectures operate.",
        },
        {
          title: "Write Superior Prompts",
          description: "Learn effective and structured prompt engineering methodologies specifically crafted for technical issues.",
        },
        {
          title: "Direct IT Application",
          description: "Discover how to immediately deploy AI for code generation, code reviews, troubleshooting, and documentation.",
        },
        {
          title: "Ensure Privacy & Security",
          description: "Know exactly what can and cannot be entered in compliance with GDPR regulations, and mitigate governance risks.",
        },
        {
          title: "Map Out Opportunities",
          description: "Identify strategic AI opportunities inside your organization and establish a concrete roadmap.",
        },
      ],
    },
    audience: {
      title: "Who is this training for?",
      subtitle: "Specially designed for IT professionals wanting to apply AI practically",
      description: "This course is developed for IT professionals who want to understand how Artificial Intelligence (AI) is shifting their profession and how to utilize AI directly in their daily workflow. No prior experience with AI is required. A general IT background is sufficient.",
      requirementsTitle: "Prerequisites",
      requirementsText: "You do not need any prior experience with Artificial Intelligence. However, a general background in IT is highly recommended.",
      tasksTitle: "Ideal if you regularly perform:",
      tasksList: [
        "Software development or maintenance",
        "System and network administration",
        "Troubleshooting and incident management",
        "Writing technical documentation",
        "Analyzing log files",
        "Managing system configurations",
        "Security and compliance audits",
        "Automation of recurring IT processes",
      ],
      idealTitle: "This training is perfect if:",
      idealList: [
        "You want to understand what everyone is talking about regarding AI.",
        "You want to speak confidently about AI starting next Monday.",
        "You want to save time on repetitive, time-consuming tasks.",
        "You want to use AI safely, securely, and responsibly.",
        "You are looking for a practical course without dense academic theories.",
      ],
      notForTitle: "When is this training not suitable?",
      notForText: "This is an introductory course for IT professionals. If you are already doing advanced prompt engineering, training your own models, or looking for dense machine learning mathematics, an advanced AI engineering course would fit your knowledge level better.",
    },
    program: {
      title: "Course Schedule",
      subtitle: "An intensive, practical one-day agenda from 09:00 to 17:00",
      timeline: [
        {
          time: "09:00 – 09:30",
          title: "Introduction & AI Landscape",
          description: "We start the day with introductions and explore the current landscape of AI.",
        },
        {
          time: "09:30 – 10:45",
          title: "Understanding how AI works",
          description: "Discover how Large Language Models (LLMs) operate under the hood.",
        },
        {
          time: "10:45 – 11:00",
          title: "Morning Break",
          description: "A brief break for coffee and tea.",
        },
        {
          time: "11:00 – 12:30",
          title: "Prompting for IT Professionals",
          description: "Learn to write structured, effective prompts.",
        },
        {
          time: "12:30 – 13:15",
          title: "Catered lunch",
          description: "Enjoy a healthy, fully catered lunch.",
        },
        {
          time: "13:15 – 14:45",
          title: "AI as your software assistant",
          description: "Discover how to utilize AI as an assistant.",
        },
        {
          time: "14:45 – 15:00",
          title: "Afternoon Break",
          description: "A quick break to refresh and recharge your energy.",
        },
        {
          time: "15:00 – 16:00",
          title: "Security, Privacy, and Governance",
          description: "Learn how to use AI safely, GDPR-compliantly, and responsibly.",
        },
        {
          time: "16:00 – 17:00",
          title: "Workshop: AI Use Cases inside your Organization",
          description: "Map out concrete AI opportunities within your own organization.",
        },
      ],
    },
    practical: {
      title: "Practical Information",
      subtitle: "Everything you need to know to start the course fully prepared",
      dateLabel: "Date",
      dateValue: "Saturday September 26, 2026",
      locationLabel: "Location",
      locationValue: "Noordenweg 24, Ridderkerk (NL)",
      locationDetails: "Highly accessible venue. Exact room and route directions will be provided immediately upon registration.",
      timeLabel: "Time",
      timeValue: "09:00 AM – 05:00 PM",
      timeDetails: "Doors open at 08:45 AM. Arrive early to grab a warm cup of coffee or tea!",
      includesLabel: "Included",
      includesList: [
        "Full intensive 1-day course",
        "Fresh, healthy gourmet lunch",
        "Unlimited coffee, tea, sodas, and refreshments",
        "A healthy dose of humor and inspiration",
      ],
      bringLabel: "What to bring?",
      bringValue: "Your own laptop",
      bringRecommended: [
        "A laptop with Wi-Fi capability",
        "Access to an AI tool such as ChatGPT (a free tier account is perfectly fine)",
      ],
      groupSizeLabel: "Group Size",
      groupSizeValue: "Maximum 10 participants",
      levelLabel: "Level",
      levelValue: "Beginner to Intermediate",
      levelDetails: "No advanced AI background needed. A general understanding of IT processes or systems is sufficient.",
      investmentLabel: "Investment",
      originalPrice: "€799",
      discountPrice: "€199",
      priceDetails: "Temporary promotional / Early Bird discount. Prices are per person and include catering and drinks. A professional invoice will be provided.",
      afterRegisterLabel: "After Registration",
      afterRegisterValue: [
        "Immediate confirmation email with receipt and next steps.",
      ],
    },
    trainer: {
      title: "Trainers & Foundation",
      subtitle: "Learn from seasoned IT professionals who live and breathe responsible AI",
      intro: "This training is delivered by active IT veterans representing the Sustainable AI Foundation (Stichting Duurzaam AI). We avoid purely academic theories and focus entirely on a hands-on approach derived from daily IT realities.",
      aboutFoundationTitle: "About the Sustainable AI Foundation",
      aboutFoundationText: "Stichting Duurzaam AI (Sustainable AI Foundation) empowers professionals and organizations to apply Artificial Intelligence in practical, secure, and highly responsible ways. We look past the marketing hypes and focus on the core question: How can AI advancements move hand-in-hand with human values, strict data compliance, and ethics?",
      trainerCardTitle: "Meet your Instructors",
      trainers: [
        {
          name: "Sayf Jawad",
          role: "Software Architect & AI Specialist",
          bio: "Sayf has over 15 years of experience in software development, software architecture, and AI. He helps organizations build future-proof software and responsibly deploy generative AI, with a strong focus on quality, privacy, and practical applicability.",
          initials: "SJ",
          experience: "15+ years experience in Software & AI",
          linkedinUrl: "https://www.linkedin.com/in/sayf-jawad-511100300/",
        },
        {
          name: "Manhal AL-Rubaiy",
          role: "Senior Data & AI Engineer",
          bio: "Manhal has over 15 years of experience in Business Intelligence, data engineering, and AI. He helps organizations and IT professionals apply generative AI safely and practically, delivering immediately usable solutions for daily operations.",
          initials: "MA",
          experience: "15+ years experience in Data & AI",
          linkedinUrl: "https://www.linkedin.com/in/manhal-al-rubaiy",
        },
      ],
      approachTitle: "Our Methodology",
      approachIntro: "We believe AI only brings real, lasting value when professionals understand how it behaves, where its security vulnerabilities lie, and how to govern it safely. Thus we combine:",
      approachPoints: [
        "Decades of hands-on IT engineering experience",
        "Up-to-date and rigorous AI knowledge",
        "Live technical demonstrations on active systems",
        "Highly realistic, relatable practical cases",
        "Interactive, engaging hands-on exercises",
      ],
    },
    faq: {
      title: "Frequently Asked Questions",
      subtitle: "Answers to common questions about the course and registration",
      items: [
        {
          question: "Do I need prior experience with Artificial Intelligence?",
          answer: "No, absolutely not. This course is specifically built for IT professionals who want to understand AI's core capabilities from scratch. A general background in IT operations, support, management, or development is all you need.",
        },
        {
          question: "Do I need to be a programmer to join?",
          answer: "No. Although we use code-related snippets and automation examples in the software assistant segment, the core focus is on prompting, evaluating outputs, and governance. Systeembeheerders, network engineers, project managers, and IT support pros will find it highly accessible and relevant.",
        },
        {
          question: "Can my employer pay for this training?",
          answer: "Yes, certainly! The vast majority of our participants have this course fully funded by their employers. Upon registration, you will receive a professional VAT-compliant invoice that can be submitted to your organization's finance or HR department.",
        },
        {
          question: "What concrete skills will I gain by the end of the day?",
          answer: "You will understand LLM behaviors, know how to craft structured prompts that deliver precise technical results, use AI safely as an everyday programming and documentation co-pilot, handle data in compliance with GDPR guidelines, and learn to audit and prioritize AI opportunities within your own enterprise.",
        },
        {
          question: "Which specific AI tools are covered?",
          answer: "We demonstrate and work with several leading systems (including ChatGPT, Microsoft Copilot, and popular IDE extensions). However, the focus remains on foundational concepts and flexible prompting patterns, so you can easily master any AI tool that emerges in the future.",
        },
        {
          question: "Do I need to bring my own laptop?",
          answer: "Yes. Because the course is highly interactive and features multiple practical challenges, you will need your own machine. We advise bringing a laptop with Wi-Fi capabilities and having a (free) account set up on ChatGPT.",
        },
        {
          question: "Is lunch included in the price?",
          answer: "Yes, completely! The course is fully catered. A comprehensive buffet lunch, unlimited coffee, tea, cold drinks, and sweet/savory snacks are included at no extra cost.",
        },
        {
          question: "What is the cancellation policy?",
          answer: "You can cancel free of charge up to 14 days before the event. Cancellations within 14 days are subject to a 50% fee. Cancellations within 7 days or no-shows are subject to 100% of the registration fee. If you are unable to attend, you may send a replacement colleague at no extra charge, provided you notify us via email at least one business day beforehand.",
        },
      ],
    },
    stats: {
      eyebrow: "BY THE NUMBERS",
      title: "Statistics",
      subtitle: "Live figures on interest in this training.",
      seatsLabel: "Available seats",
      seatsFilled: "seats filled",
      seatsFull: "Full",
      totalRegistrations: "Registrations",
      totalVisitors: "Website visits",
      experienceBreakdownTitle: "Participants' IT experience",
      loading: "Loading statistics...",
      error: "Could not load statistics.",
    },
    registration: {
      title: "Enroll & Secure Your Seat",
      subtitle: "Register now for the course on Saturday September 26, 2026. Note: strictly limited to 10 participants!",
      formTitle: "Registration Form",
      personalData: "Personal Information",
      firstName: "First Name *",
      lastName: "Last Name *",
      email: "Email Address *",
      phone: "Phone Number",
      workData: "Company & Experience",
      organization: "Organization",
      function: "Job Title",
      experience: "Years of IT Experience",
      experienceOptions: ["0–2 years", "3–5 years", "5–10 years", "10+ years"],
      invoiceData: "Invoice details",
      invoiceRequired: "Invoice billed to your company?",
      invoiceRequiredYes: "Yes, bill my company/employer",
      invoiceRequiredNo: "No, personal invoice",
      companyName: "Company Name *",
      invoiceAddress: "Invoice Address *",
      postalCodeCity: "Postal Code & City *",
      vatNumber: "VAT Number (if applicable)",
      dietaryLabel: "Do you have dietary requirements?",
      dietaryOptions: [
        { label: "No requirements", value: "Geen" },
        { label: "Vegetarian", value: "Vegetarisch" },
        { label: "Vegan", value: "Vegan" },
        { label: "Allergy / Other", value: "Allergie" },
      ],
      dietaryPlaceholder: "Specify any food allergies or requirements...",
      remarksLabel: "Remarks or Questions",
      remarksPlaceholder: "Any special requests or details you'd like to share...",
      consentTerms: "I agree to the general terms and conditions of Stichting Duurzaam AI. *",
      consentPrivacy: "I have read the privacy policy and agree to the processing of my data for this registration. *",
      submitBtn: "Reserve my spot",
      submitting: "Processing...",
      successTitle: "Reservation Successfully Received!",
      successText: "Congratulations! Your seat for the 'AI for IT Professionals' training course on Saturday September 26, 2026 has been successfully reserved.",
      successSteps: [
        "You will receive an automated confirmation email of your reservation immediately, containing the next steps.",
        "Email not received? Please check your spam or junk folder first. If you still cannot find the email there, please contact Stichting Duurzaam AI via info@stichtingduurzaamai.nl.",
      ],
      validationError: "Please fill in all required fields (*) correctly.",
      privacyLink: "Privacy Policy (GDPR)",
      termsLink: "General Terms & Conditions",
    },
    footer: {
      tagline: "Stichting Duurzaam AI - Moving together towards a responsible, secure, and sustainable AI future.",
      contact: "Contact Information",
      rights: "© 2026 Stichting Duurzaam AI. All rights reserved.",
      privacy: "Privacy Policy",
      terms: "Terms & Conditions",
      adminPanel: "Admin Dashboard (Registrations)",
    },
  },
};
